config/routes.rb
TodoTddApp::Application.routes.draw do
  root to: 'Tasks#index'

  resources :tasks

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  	@tasks = Task.all
  	@task = Task.new
  end

  def create
  	Task.create(params[:task])
  	redirect_to root_path
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "ToDo World"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end			
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ToDo World
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ToDo World", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>This is the about page.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>This is the contact page.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page.</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to ToDo World!</h1>

  <h2>
    This is the home page.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= form_for @task do |f| %>
	<%= f.label :task %>
	<%= f.text_field :task %>
	<%= f.submit %>	
<% end %>

<ul>
	<% @tasks.each do |task| %>
		<li>
			<%= task.task %> | <%= link_to 'Edit', edit_task_path(task) %>
		</li>
	<% end %>
</ul>		